export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const PUBLIC_DATA_SUCCESS = 'PUBLIC_DATA_SUCCESS'
export const PUBLIC_DATA_STARTED = 'PUBLIC_DATA_STARTED'
export const PUBLIC_DATA_ERROR = 'PUBLIC_DATA_ERROR'

