export const NAV_DATA_SUCCESS = 'NAV_DATA_SUCCESS'
export const NAV_DATA_ERROR = 'NAV_DATA_ERROR'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_STARTED = 'AUTH_STARTED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const PUBLIC_DATA_SUCCESS = 'PUBLIC_DATA_SUCCESS'
export const PUBLIC_DATA_STARTED = 'PUBLIC_DATA_STARTED'
export const PUBLIC_DATA_ERROR = 'PUBLIC_DATA_ERROR'

export const EDITOR_SEND_SUCCESS = 'PUBLIC_DATA_SUCCESS'
export const EDITOR_SEND_STARTED = 'PUBLIC_DATA_STARTED'
export const EDITOR_SEND_ERROR = 'PUBLIC_DATA_ERROR'
