export const NAV_DATA_SUCCESS = 'NAV_DATA_SUCCESS'
export const NAV_DATA_ERROR = 'NAV_DATA_ERROR'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_STARTED = 'AUTH_STARTED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const EDITOR_SEND_SUCCESS = 'EDITOR_SEND_SUCCESS'
export const EDITOR_SEND_STARTED = 'EDITOR_SEND_STARTED'
export const EDITOR_SEND_ERROR = 'EDITOR_SEND_ERROR'

export const TEACHERS_SUCCESS = 'TEACHERS_SUCCESS'
export const TEACHER_SUCCESS = 'TEACHER_SUCCESS'
export const USERS_SEND_SUCCESS = 'USERS_SEND_SUCCESS'
export const USERS_SEND_STARTED = 'USERS_SEND_STARTED'
export const USERS_SEND_ERROR = 'USERS_SEND_ERROR'
